name: Terraform Destroy

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production   # <-- triggers approval

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/882388401722/locations/global/workloadIdentityPools/terraform-pool/providers/github"
          service_account: "terraform-sa@project-96d8ec0c-24f0-4d1c-bb4.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Destroy Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
