name: Terraform

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/882388401722/locations/global/workloadIdentityPools/terraform-pool/providers/github"
          service_account: "terraform-sa@project-96d8ec0c-24f0-4d1c-bb4.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # - name: Manual Approval
      #   uses: trstringer/manual-approval@v1
      #   with:
      #     approvers: "ambatis186@gmail.com, ambatisathishkumarreddy@gmail.com, sahanasan242@gmail.com"
      #     minimum-approvals: 1

      - name: Terraform Apply
        run: terraform apply -auto-approve
